---
- hosts: vps
  gather_facts: False
  become_user: marco
  tasks:
    - name: "Check and "
      become_user: root
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
