---
# The computer needs to have its id_rsa.pub registered in your in github
- hosts: vps
  vars:
    home: "{{ ansible_env.HOME }}"
    workspace: "{{ home }}/dev"
  tasks:

      # - name: debug through ansible.env
      #   debug: var="{{item}}"
      #   with_items:
      #   - home
      #   - workspace

    - name: "Setup Python"
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: "Make workspace folder"
      file:
        path:
          - "{{ workspace }}"
        state: directory

    - name: "Install Dependencies"
      become: true
      apt:
        name:
          - git
          - fish
          - python-pip
        update_cache: yes
      pip:
        name: docker-py

    - name: "Clone fish-config"
      git:
        repo: https://github.com/marco-souza/fish-config.git
        dest: "{{ workspace }}/fish-config"
        clone: yes
        recursive: yes

    - name: Apply fish config
      shell: make
      args:
        chdir: "{{ workspace }}/fish-config"

    - name: Replace bash
      command: "echo -e '\n\n# start fish\nfish; exit' >> {{ home }}/.bashrc"
